development:
  adapter: postgresql
  encoding: unicode
  database: my_project_development
  pool: 5
  username: postgres
  password: andre
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: my_project_development
  pool: 5
  username: postgres
  password: andre
  host: localhost  

production:
  adapter: postgresql
  encoding: unicode
  database: marketplace_development
  pool: 5
  username: postgres
  password: andre
  host: localhost